### ISSUE TITLE
Crash on stock Kinetic install

### ISSUE THREAD

**Issue by VorpalBlade** [ros-visualization/rqt_nav_view#4]
Not quite sure what is going, or how to use this plugin at all, but when I try to run it, it just crashes after a couple of seconds (the GUI does show up first). Maybe the plugin has undocumented expectations that are not valid in my environment?

```
$ rosrun rqt_nav_view rqt_nav_view 
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_nav_view/nav_view.py", line 456, in _update
    self._mirror(self._map_item)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_nav_view/nav_view.py", line 491, in _mirror
    item.scale(-1, 1)
TypeError: QGraphicsItem.scale(): too many arguments
```

**Comment by MatthijsBurgh** [comment]
I got this issue on melodic as well
